# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Checklists
    url: checklists/
    weight: 20
  - name: Biography
    url: uses/
    weight: 30
